services:
  - type: web
    name: explorador-cosmico
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.3
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: explorador_db
          property: connectionString

databases:
  - name: explorador_db
    databaseName: explorador_cosmico
    user: explorador_user